
var buttonColors=["red","blue","green","yellow"];
//gamePattern is used to keep track of the pattern generated by the machine.
var gamePattern=[];
//userClickedPattern keeps track of the click pattern by the user at each and every lvl.
var userClickedPattern=[];
var level=0;

//To start the game on any key pressed in KeyBoard.
$(document).on('keypress',nextSequence);

// To generate the next sequence of the game.
function nextSequence()
{
    userClickedPattern=[];
    $("#level-title").text("Level "+level);
    var randomNumber=Math.floor(Math.random() * 4);
    var randomChoosenColor=buttonColors[randomNumber];
    gamePattern.push(randomChoosenColor);
    $("#"+randomChoosenColor).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChoosenColor);
    level=level+1;
    
}

//To detect which button is clicked
$(".btn").on("click",function()
{
    var userChoosenColor=$(this).attr("id");
    userClickedPattern.push(userChoosenColor);
    playSound(userChoosenColor);
    animatePress(userChoosenColor);
    checkAnswer(userClickedPattern.length-1);

}
);

//To generate the sound 
function playSound(name)
{
    var audio=new Audio("sounds/"+name+".mp3");
    audio.play();

}

//To animate button on each click.
function animatePress(currentColor)
{
    $("#"+currentColor).addClass("pressed");
    setTimeout(function() { 
        $("#"+currentColor).removeClass("pressed");
    }, 100);
}

function checkAnswer(currentLevel)
{
   if(gamePattern[currentLevel]===userClickedPattern[currentLevel])
   {
    
    if(userClickedPattern.length===gamePattern.length)
    {
        setTimeout(function () {
            nextSequence();
          }, 1000);
    }
   }
   else
   {
    playSound("wrong");
    $("body").addClass("game-over");
    setTimeout(function() { 
        $("body").removeClass("game-over");
    }, 200);
    $("#level-title").text("Game Over, Press Any Key to Restart");
    startOver();

   }

}

function startOver()
{
    level=0;
    gamePattern=[];
    userClickedPattern=[];
}